export const Get_PRODUCT="GET_PRODUCT";
export const GET_SINGLE_PRODUCT="GET_SINGLE_PRODUCT";
export const GET_RECOMMENDED_PRODUCT="GET_RECOMMENDED_PRODUCT";
export const DELETE_PRODUCT="DELETE-PRODUCT"
export const GET_CATEGORIES="GET_CATEGORIES"
export const DELETE_CATEGORY="DELETE-CATEGORY"
export const GET_USER="GET_USER";
export const DELETE_USER="DELETE_USER"
